# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LZ_GzGS8y23tWmfvIXEYQ-2C0aZoPWzX
"""

!pip install yfinance pandas matplotlib seaborn

# ==============================
# 1. Install & import libraries
# ==============================
!pip install yfinance

import yfinance as yf
import pandas as pd
import matplotlib.pyplot as plt
from google.colab import files
companies = {
    "AAPL": "1y",
    "NVDA": "6mo",
    "TSLA": "3mo",
    "AMZN": "9mo",
    "MSFT": "1mo"
}

data = {}
for ticker, period in companies.items():
    df = yf.Ticker(ticker).history(period=period)
    df.reset_index(inplace=True)
    filename = f"{ticker}.csv"
    df.to_csv(filename, index=False)

    data[ticker] = df

    print(f"Saved: {filename}")
for ticker, df in data.items():
    print(f"\n===== {ticker} Statistics =====")
    print(df.describe())
for ticker, df in data.items():
    print(f"\n===== {ticker} KPI CHECK =====")
    print("Missing values:\n", df.isnull().sum())
    print("Latest date:", df["Date"].max())
    if (df["Close"] < 0).any():
        print("Warning: Negative prices found!")
    else:
        print("No negative prices (OK)")
    print("Columns:", list(df.columns))
for ticker, df in data.items():
    plt.figure()
    plt.plot(df["Date"], df["Close"])
    plt.title(f"{ticker} Closing Prices")
    plt.xlabel("Date")
    plt.ylabel("Price")
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.show()
plt.figure()

for ticker, df in data.items():
    plt.plot(df["Date"], df["Close"], label=ticker)

plt.title("Stock Price Comparison")
plt.xlabel("Date")
plt.ylabel("Price")
plt.legend()
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()
for ticker in companies.keys():
    files.download(f"{ticker}.csv")